### ISSUE TITLE
Error handling/ notifications on add product

### ISSUE THREAD

**Issue by Brela** [DallasSoftwareDevelopersTeamC/orderly#226]
When adding product, notify user if any fields have wrong types

Currently it will just not work and not notify the user what the problem is if the filed is supposed to be a number but isn't

**Comment by joshuaow91** [comment]
This is resolved. a toast notification will appear with an error message directed at the specific field in question. Stock, reorder, order qty, and cost will display a number is required in this field. success and other error message added as well
