### ISSUE TITLE
Get selected inventory rows from react-table into inventory.context

### ISSUE THREAD

**Issue by Brela** [DallasSoftwareDevelopersTeamC/orderly#239]
This will allow useTempInStock hook to have has access to it

**Comment by joshuaow91** [comment]
rows can now be toggled, the button at the top will open a pop up with info for these rows. now the logic from the previous checkbox component needs to be implemented.

**Comment by joshuaow91** [comment]
implemented react-table "useRowSelect" created a modal that displays the data of selected rows. used the deleteInventoryItems to attempt item deletion, worked through errors. after that, the log showed the data passed from table was an empty array.  attempted another way to pass data to modal, this now allowed me to get the ID to delete items. items now delete without any errors on client or server but the deleteInventoryItems in the inventory controllers says no items deleted and the ui still displays the item. this is where i left it at. will continue on this..

**Comment by joshuaow91** [comment]
Data is correctly displaying from the selected rows in the modal. the delete function now works. the backend controller threw an error for a foreign key constraint which is the sample data matched the data for other users. needed to add the user id so the delete logic would delete a user-specific item.
